### PR TITLE
[ADD]: Webservice to generate a PDF and cancel XML task#9290

### PR DESCRIPTION
**Pull request by goliveirab**
**Generate payslip**
PDF With a signed payroll XML : Generate the PDF

**Cancel payslip**
With a UUIDs list: Cancel the XML in SAT.

### CODE REVIEW

**Comment by goliveirab** [comment]
@luistorresm 
This changes copy the test payroll, i still have to 'confirm' the payroll to generate the xml (not signed), so i was trying to call the `hr_verify_sheet` with `hr_payslip.execute_kw(DB_NAME, UID, PASSWD, 'hr.payslip',  'hr_verify_sheet', [cr, uid, [hr_copy]]) ` but, How could i get the cursor (cr) in the WS to pass it to the method?

**Comment by goliveirab** [comment]
@luistorresm 
Could you please check this.

**Comment by luistorresm** [comment]
Thanks @goliveirab 

Could you show me the PDF that generate the WS, please?

**Comment by goliveirab** [comment]
@luistorresm 
This is the PDF:
[Page 1](https://drive.google.com/a/vauxoo.com/file/d/0B4jIZfjtBteKeFREYjF4R3hrUkE/view?usp=drivesdk)
[Page 2](https://drive.google.com/a/vauxoo.com/file/d/0B4jIZfjtBteKSmlSUl95alpQWE0/view?usp=drivesdk)

**Comment by goliveirab** [comment]
@luistorresm 
I made some changes here: https://github.com/Vauxoo/odoo-mexico-v2/pull/441 in the report to set the 'Receptor' values. And now the PDF is like this: [PDF](https://drive.google.com/a/vauxoo.com/file/d/0B4jIZfjtBteKUFRCZDFJbXMyTzQ/view?usp=drivesdk)

**Comment by goliveirab** [comment]
@luistorresm 
could you please check this.

**Comment by goliveirab** [comment]
@luistorresm 
The file `ws_cancel_payslip_xml.py` has been created for the cancellation process.

**Comment by goliveirab** [comment]
@luistorresm 
Do you have any news about this?

**Pull request merged**
